tes

diff --git a/scripts/auto-create-repo b/scripts/auto-create-repo
--- a/scripts/auto-create-repo
+++ b/scripts/auto-create-repo
@@ -9,16 +9,17 @@ do
   sleep 5
 done
 
-if curl https://api.github.com/repos/Alexandrazhao/$NAME; then
-    echo '%s\n' "The GitHub repo $NAME exists this is me." >&2
-else
-    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
-fi
-sleep 20
+#if curl https://api.github.com/repos/Alexandrazhao/$NAME; then
+#    echo '%s\n' "The GitHub repo $NAME exists this is me." >&2
+#else
+#    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
+#fi
+#sleep 20
 
 curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
     --data '{"name":"'$NAME'"}'\
-    https://api.github.com/user/repos
+    https://api.github.com/user/repos/text.txt
+
 
 
 
