h

diff --git a/scripts/auto-create-repo b/scripts/auto-create-repo
--- a/scripts/auto-create-repo
+++ b/scripts/auto-create-repo
@@ -15,18 +15,18 @@ curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
     https://api.github.com/user/repos
 
 
-#if curl -fsS "https://api.github.com/repos/$MY_REPO" >/dev/null; then
-#    echo '%s\n' "The GitHub repo $MY_REPO exists this is me." >&2
-#    return 0
-#else
-#    printf '%s\n' "Error: no GitHub repo $MY_REPO found." >&2
-#    return 1
-#fi
-
-if [ "$MY_REPO" = "$NAME" ]; then
-    echo "Strings are equal."
+if curl -fsS "https://api.github.com/repos/$NAME" >/dev/null; then
+    echo '%s\n' "The GitHub repo $NAME exists this is me." >&2
+    return 0
 else
-    echo "Strings are not equal. my-repo is $MY_REPO, my name is $NAME"
+    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
+    return 1
 fi
+
+#if [ "$MY_REPO" = "$NAME" ]; then
+#    echo "Strings are equal."
+#else
+#    echo "Strings are not equal. my-repo is $MY_REPO, my name is $NAME"
+#fi
 
 
