s

diff --git a/scripts/auto-create-repo b/scripts/auto-create-repo
--- a/scripts/auto-create-repo
+++ b/scripts/auto-create-repo
@@ -14,21 +14,13 @@ curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
     --data '{"name":"'$NAME'"}'\
     https://api.github.com/user/repos
 
-if $MY_REPO == $NAME; then echo "SAME!!!" fi
 
-
-
-
-exists_repo(){
-    if curl -fsS "https://api.github.com/repos/$MY_REPO" >/dev/null; then
-        printf '%s\n' "The GitHub repo $MY_REPO exists this is me." >&2
-        return 0
-    #else
-    #    printf '%s\n' "Error: no GitHub repo $MY_REPO found." >&2
-    #    return 1
-    fi
-}
-
-if exists_repo "'$MY_REPO'/'$NAME'"; then
-  echo "no!"
+if curl -fsS "https://api.github.com/repos/$MY_REPO" >/dev/null; then
+    echo '%s\n' "The GitHub repo $MY_REPO exists this is me." >&2
+    return 0
+#else
+#    printf '%s\n' "Error: no GitHub repo $MY_REPO found." >&2
+#    return 1
 fi
+
+
