add new

diff --git a/scripts/auto-create-repo b/scripts/auto-create-repo
--- a/scripts/auto-create-repo
+++ b/scripts/auto-create-repo
@@ -9,11 +9,11 @@ do
   sleep 5
 done
 
-#if curl https://api.github.com/repos/Alexandrazhao/$NAME; then
-#    echo '%s\n' "The GitHub repo $NAME exists this is me." >&2
-#else
-#    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
-#fi
+if curl -fsS "https://api.github.com/repos/Alexandrazhao/$NAME" >/dev/null; then
+    printf '%s\n' "The GitHub repo $NAME exists." >&2
+else
+    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
+fi
 #sleep 20
 
 curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
